# Generated by Django 5.0.4 on 2024-04-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadfilmes', '0002_filmes_url_do_filme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmes',
            name='url_do_filme',
            field=models.URLField(max_length=500),
        ),
    ]
